import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '../styles/custom.scss';
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <nav className="navbar navbar-expand-lg navbar-light bg-light shadow-sm mb-4" style={{ fontFamily: 'Vazirmatn', direction: 'rtl' }}>
          <div className="container-fluid">
            <Link className="navbar-brand fw-bold" href="/dashboard">راز دل</Link>
            <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNav" aria-controls="mainNav" aria-expanded="false" aria-label="تغییر منو">
              <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="mainNav">
              <ul className="navbar-nav ms-auto mb-2 mb-lg-0" style={{ gap: 12 }}>
                <li className="nav-item"><Link className="nav-link" href="/dashboard">داشبورد</Link></li>
                <li className="nav-item"><Link className="nav-link" href="/newmessage">ارسال پیام</Link></li>
                <li className="nav-item"><Link className="nav-link" href="/messagebox">صندوق پیام</Link></li>
                <li className="nav-item"><Link className="nav-link" href="/profile">پروفایل</Link></li>
                <li className="nav-item"><Link className="nav-link" href="/setting">تنظیمات</Link></li>
                <li className="nav-item"><Link className="nav-link" href="/meditation">مدیتیشن</Link></li>
                <li className="nav-item"><Link className="nav-link" href="/about">درباره ما</Link></li>
                <li className="nav-item"><Link className="nav-link" href="/contact">تماس با ما</Link></li>
                <li className="nav-item"><Link className="nav-link text-danger" href="/login">خروج</Link></li>
              </ul>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
